name: auto_drive
description: Car management application
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.18.2 <3.13.4'


dependencies:
  flutter:
    sdk: flutter

  #mandatory
  bloc:
  flutter_bloc:
  freezed_annotation:
  http:
  flutter_launcher_icons:
  injectable: #dependency injection
  get_it: #service locator #getIT and injectable are needed
  auto_route: #routing

  flutter_svg:
  fpdart: #functional programming
  html:
  uuid:
  cupertino_icons:
  money2:
  drift:
  mystique:



dev_dependencies:
  flutter_test:
    sdk: flutter

  #mandatory
  flutter_lints:
  build_runner:
  freezed:
  injectable_generator:
  auto_route_generator:


flutter:
  uses-material-design: true
  assets:
    - assets/images/auto_drive.png
    - assets/images/avatar.png
    - assets/icons/garage_icon.png
    - assets/images/auto_drive_logo_transparent_200x200.png
    - assets/images/car_line.jpg
    - assets/images/lambo.png
    - assets/images/graph.png


#providing the icon app
flutter_launcher_icons:
  image_path: "assets/images/auto_drive_logo_transparent_200x200.png"
  android: true
  ios: true
  remove_alpha_ios: true

  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
