name: auto_drive
description: Car management application
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  html: ^0.15.0
  uuid: 3.0.6
  cupertino_icons: ^1.0.2
  money2: ^3.3.0
  drift: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/auto_drive.png
    - assets/images/avatar.png
    - assets/icons/garage_icon.png


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
