name: Deploy to Play Store

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - Checkout repository
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # - name: Build AAB
      #   run: flutter build appbundle --release

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
          packageName: your.package.name # replace with your app's package name
          releaseFiles: build/app/outputs/flutter-apk/app-release.apk
          # releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: alpha  # or alpha, beta, internal
